spring:

  kafka:
    template:
      default-topic: library-events
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 10
      properties:
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
#        retries: 10
      ssl:
        trust-store-location: 'file:\D:\MyProjects\study\kafka-starter\secrets\kafka.producer.truststore.jks'
        trust-store-password: confluent
        key-store-location: 'file:\D:\MyProjects\study\kafka-starter\secrets\kafka.producer.keystore.jks'
        key-store-password: confluent
    admin:
      properties:
        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094